int32 action
amrl_msgs/Pose2Df goal_pose
geometry_msgs/Pose2D loc
nav_msgs/Odometry odom
sensor_msgs/LaserScan laser
float64 time
geometry_msgs/Pose2D[] human_poses
geometry_msgs/Pose2D[] human_vels
---
float32 cmd_vel
float32 cmd_curve
geometry_msgs/Pose2D local_target
int32 target_id
