//========================================================================
//  This software is free: you can redistribute it and/or modify
//  it under the terms of the GNU Lesser General Public License Version 3,
//  as published by the Free Software Foundation.
//
//  This software is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU Lesser General Public License for more details.
//
//  You should have received a copy of the GNU Lesser General Public License
//  Version 3 in the file COPYING that came with this distribution.
//  If not, see <http://www.gnu.org/licenses/>.
//========================================================================
/*!
\file    deep_cost_map_evaluator_service.h
\brief   Path rollout evaluator using a NN learned via deep IRL.
\author  Arthur K. Zhang (C) 2025
*/
//========================================================================

#include <string>
#include <vector>
#include <mutex>
#include <memory>
#include <condition_variable>

#include "ros/ros.h"
#include "amrl_msgs/CostmapSrv.h"

#include "motion_primitives.h"
#include "image_based_evaluator.h"
#include "shared/util/timer.h"
#include "navigation_parameters.h"
#include "navigation_types.h"

#include <cv_bridge/cv_bridge.h>
#include <opencv2/opencv.hpp>
#include <image_transport/image_transport.h>

#ifndef DEEP_COST_MAP_EVALUATOR_SERVICE_H
#define DEEP_COST_MAP_EVALUATOR_SERVICE_H

namespace motion_primitives {

class DeepCostMapEvaluatorService : public PathEvaluatorBase {
  public:
    DeepCostMapEvaluatorService(const navigation::NavigationParameters& params);

    std::shared_ptr<PathRolloutBase> FindBest(
      const std::vector<std::shared_ptr<PathRolloutBase>>& paths) override;

    /**
     * Generates an RGB image to visualize the scalar image generated by
     * GetScalarCostImage
     */
    cv::Mat3b GetRGBCostImage(const cv::Mat1f& scalar_cost_map);

    // Calls ros service to obtain costmap image, transforms to odom frame that was passed in
    void UpdateMap(const navigation::Odom& odom);

    std::vector<float> GetLearnedPathCosts() const override;

    /**
     * Annotates the latest_costmap_ with intermediate points along each path
     * option with colors corresponding to the relative cost of the path.
     *
     * Implicitly uses scalar costmap image and path_costs_ vector, intended to
     * be called inside of FindBest after the cost of each path ahs been
     * calculated. Overwrites the latest_vis_image_ image.
     */
    void DrawPathCosts(const std::vector<std::shared_ptr<PathRolloutBase>>& paths,
                     std::shared_ptr<PathRolloutBase> best_path);

    cv::Mat3b latest_vis_image_;  // Latest visualization image
  private:
    ros::NodeHandle nh_;                 // ROS node handle
    ros::ServiceClient service_client_;  // ROS service client
    navigation::NavigationParameters params_;
    std::mutex mutex_;            // Mutex for thread-safe access
    std::condition_variable cv_;  // Condition variable for blocking
    bool service_request_ongoing_;  // Indicates if a service request is ongoing

    std::vector<float> learned_path_costs_;  // Learned cost of each path
    std::vector<float> path_costs_;  // Cost of each path
    cv::Mat1f latest_costmap_;      // Latest cost map
    cv::Mat1f prev_costmap_;       // Last up to date cost map
    navigation::Odom prev_odom_;              // Last up to date odometry message
    bool has_map_;          // Indicates if a map exists

    // Computes nonlinear clearance weight
    float ClearanceCost(const std::shared_ptr<PathRolloutBase> &path);

    // Called by UpdateMap to update map to local frame
    void UpdateMapToLocalFrame(const cv::Mat1f& costmap, const navigation::Odom& prev_odom, const navigation::Odom& odom);

    // Returns sum of costs along each path
    std::vector<float> GetLearnedCosts(
      const std::vector<std::shared_ptr<PathRolloutBase>>& paths, const cv::Mat1f& cost_map);

    // Updates costmap
    void RequestMapUpdate(const navigation::Odom& odom);

    // Maps cost to colormap
    cv::Vec3b GetColorFromCost(float cost);

};

}  // namespace motion_primitives

#endif  // DEEP_COST_MAP_EVALUATOR_H