//========================================================================
//  This software is free: you can redistribute it and/or modify
//  it under the terms of the GNU Lesser General Public License Version 3,
//  as published by the Free Software Foundation.
//
//  This software is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU Lesser General Public License for more details.
//
//  You should have received a copy of the GNU Lesser General Public License
//  Version 3 in the file COPYING that came with this distribution.
//  If not, see <http://www.gnu.org/licenses/>.
//========================================================================
/*!
\file    deep_cost_map_evaluator_service.h
\brief   Path rollout evaluator using a NN learned via deep IRL.
\author  Arthur K. Zhang (C) 2025
*/
//========================================================================

#ifdef ROS1
  #include <ros/ros.h>
  #include <amrl_msgs/CostmapSrv.h>  // from catkin-based amrl_msgs
#else
  #include <rclcpp/rclcpp.hpp>
  #include <amrl_msgs/srv/costmap_srv.hpp>  // from ament-based amrl_msgs
#endif

#include <cv_bridge/cv_bridge.h>
// #include <image_transport/image_transport.h>
#include <condition_variable>
#include <memory>
#include <mutex>
#include <opencv2/opencv.hpp>
#include <string>
#include <vector>

#include "motion_primitives.h"
#include "navigation_parameters.h"
#include "navigation_types.h"
#include "shared/util/timer.h"
#include "shared/math/geometry.h"

#ifndef DEEP_COST_MAP_EVALUATOR_SERVICE_H
#define DEEP_COST_MAP_EVALUATOR_SERVICE_H

namespace motion_primitives {

class DeepCostMapEvaluatorService : public PathEvaluatorBase {
 public:
#ifdef ROS1
  explicit DeepCostMapEvaluatorService(const navigation::NavigationParameters& params);
#else
  explicit DeepCostMapEvaluatorService(
    const navigation::NavigationParameters& params, rclcpp::Node::SharedPtr node);
#endif
  std::shared_ptr<PathRolloutBase> FindBest(
      const std::vector<std::shared_ptr<PathRolloutBase>>& paths) override;

  /**
   * Generates an RGB image to visualize the scalar image generated by
   * GetScalarCostImage
   */
  cv::Mat3b GetRGBCostImage(const cv::Mat1f& scalar_cost_map);

  // Calls ros service to obtain costmap image, transforms to odom frame that
  // was passed in
  void UpdateMap(const navigation::Odom& odom);

  // Returns learned cost of each path
  std::vector<float> GetLearnedPathCosts() {
    std::lock_guard<std::mutex> lock(mutex_);
    return learned_path_costs_;
  }

  // Returns the cost of each path
  std::vector<float> GetPathCosts() {
    std::lock_guard<std::mutex> lock(mutex_);
    return path_costs_;
  }

  // Computes learned cost using weights
  float ComputeLearnedCost(float cost);

  /**
   * Annotates the latest_costmap_ with intermediate points along each path
   * option with colors corresponding to the relative cost of the path.
   *
   * Implicitly uses scalar costmap image and path_costs_ vector, intended to
   * be called inside of FindBest after the cost of each path ahs been
   * calculated. Overwrites the latest_vis_image_ image.
   */
  void DrawPathCosts(const std::vector<std::shared_ptr<PathRolloutBase>>& paths,
                     int best_index);

  void UpdateImage(const cv::Mat& image);

  cv::Mat GetAnnotatedBEVImage() {
    std::lock_guard<std::mutex> lock(mutex_);
    return latest_vis_bevimage_;
  }
  cv::Mat GetAnnotatedRGBImage() {
    std::lock_guard<std::mutex> lock(mutex_);
    return latest_vis_rgbimage_;
  }

 private:
    // ---------- Conditional ROS1 or ROS2 members ----------
  #ifdef ROS1
    ros::NodeHandle nh_;
    ros::ServiceClient service_client_;  
  #else
    rclcpp::Node::SharedPtr node_;
    rclcpp::Client<amrl_msgs::srv::CostmapSrv>::SharedPtr service_client_;
  #endif

  bool callCostmapService(
    #ifdef ROS1
          amrl_msgs::CostmapSrv &srv
    #else
          amrl_msgs::srv::CostmapSrv::Request req,
          amrl_msgs::srv::CostmapSrv::Response &res
    #endif
  );

  navigation::NavigationParameters params_;
  std::mutex mutex_;              // Mutex for thread-safe access
  std::condition_variable cv_;    // Condition variable for blocking
  bool service_request_ongoing_;  // Indicates if a service request is ongoing
  std::string node_name_;         // Name of the node
  std::string service_name_;      // Name of the costmap service

  std::vector<float> learned_path_costs_;  // Learned cost of each path
  std::vector<float> path_costs_;          // Cost of each path
  cv::Mat latest_image_;             // Latest visualization image
  cv::Mat1f latest_costmap_;               // Latest cost map
  cv::Mat1f prev_costmap_;                 // Last up to date cost map
  cv::Mat map1_, map2_;                    // Rectification maps
  cv::Mat latest_vis_bevimage_;  // Latest bev visualization image
  cv::Mat latest_vis_rgbimage_;  // Latest rgb vis image

  // Used to store the persistent costmap and odometry
  cv::Mat1f persistent_costmap_;  // The accumulated (merged) costmap.
  navigation::Odom persistent_odom_;          // The odometry associated with the persistent costmap.

  navigation::Odom prev_odom_;             // Last up to date odometry message

  // High level costmap retrieval service
  cv::Mat1f RetrieveCostmapFromService(const navigation::Odom& odom);

  // Computes nonlinear clearance weight
  float ClearanceCost(const std::shared_ptr<PathRolloutBase>& path);

  // Computes the pixel coordinates for each state on costmap
  Eigen::Vector2f StateToPixel(const Eigen::Vector2f& state);

  bool ImageBoundCheck(const Eigen::Vector2i& pixel, const cv::Mat& costmap);

  std::vector<Eigen::Vector2f> GetWheelLocations(const pose_2d::Pose2Df& pose, float robot_width, float robot_length);

  // Accumulates costmaps into persistent costmap
  void AccumulateCostmap(const cv::Mat1f& newCostmap, const navigation::Odom& newOdom);

  // Called by UpdateMap to update map to local frame
  cv::Mat1f UpdateMapToLocalFrame(const cv::Mat1f& costmap,
                             const navigation::Odom& prev_odom,
                             const navigation::Odom& odom);

  // Returns sum of costs along each path
  std::vector<float> GetLearnedCosts(
      const std::vector<std::shared_ptr<PathRolloutBase>>& paths,
      const cv::Mat1f& costmap);

  // Updates costmap
  void RequestMapUpdate(const navigation::Odom& odom);

  // Maps cost to colormap
  cv::Vec3b GetColorFromCost(float cost);

  // Maps ranking to colormap
  cv::Vec3b GetColorFromRanking(int rank, int num_paths);

  // Crops and resizes image
  cv::Mat CropAndResizeImage(const cv::Mat& input_img,
                           const cv::Point& crop_center,
                           int crop_width,
                           int crop_height,
                           int out_width,
                           int out_height);
};

}  // namespace motion_primitives

#endif  // DEEP_COST_MAP_EVALUATOR_H