name: Build-Test
# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build-test:
    name: Build Test (ROS1 Noetic)
    runs-on: ubuntu-22.04
    container: ros:noetic
    
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Run package update
        run: |
          apt update
          apt dist-upgrade -y

      - name: Install Git
        run: |
          apt-get install -y git

      - name: ROSDep Update
        run: |
          rm -f /etc/ros/rosdep/sources.list.d/20-default.list || true
          rosdep init || true
          rosdep update

      - name: Install dependencies
        run: |
          apt-get install -y g++ cmake libpopt-dev \
            liblua5.1-dev libeigen3-dev \
            libjpeg8-dev libgoogle-perftools-dev \
            libsuitesparse-dev libblas-dev liblapack-dev libopenmpi-dev \
            libgoogle-glog-dev libgflags-dev libceres-dev libtbb-dev \
            ros-noetic-xmlrpcpp python-is-python3 \
            python3-rosdep python3-rosinstall python3-rosinstall-generator python3-wstool build-essential \
            ros-noetic-tf ros-noetic-angles ros-noetic-tf2-geometry-msgs ros-noetic-costmap-2d \
            ros-noetic-cv-bridge ros-noetic-image-transport

      - name: Install wget and unzip
        run: |
          apt-get update && apt-get install -y wget unzip

      # Install libtorch
      - name: Install libtorch
        run: |
          wget https://download.pytorch.org/libtorch/lts/1.8/cpu/libtorch-cxx11-abi-shared-with-deps-1.8.2%2Bcpu.zip
          unzip libtorch-cxx11-abi-shared-with-deps-1.8.2+cpu.zip -d /opt/

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Get amrl_msgs
        run: |
          source /opt/ros/noetic/setup.bash
          export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$GITHUB_WORKSPACE:$GITHUB_WORKSPACE/../amrl_msgs
          cd $GITHUB_WORKSPACE/..
          git clone https://github.com/ut-amrl/amrl_msgs.git
          cd amrl_msgs
          make

      - name: Run build
        run: |
          source /opt/ros/noetic/setup.bash
          export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$GITHUB_WORKSPACE:$GITHUB_WORKSPACE/../amrl_msgs
          cd $GITHUB_WORKSPACE
          make
